# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1067, 815)
        MainWindow.setMinimumSize(QtCore.QSize(1067, 815))
        MainWindow.setMaximumSize(QtCore.QSize(1067, 815))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 180, 671, 391))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(27)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1067, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuStudents = QtWidgets.QMenu(self.menubar)
        self.menuStudents.setObjectName("menuStudents")
        self.menuClasses = QtWidgets.QMenu(self.menubar)
        self.menuClasses.setObjectName("menuClasses")
        self.menuSubjects = QtWidgets.QMenu(self.menubar)
        self.menuSubjects.setObjectName("menuSubjects")
        self.menuEnrollments = QtWidgets.QMenu(self.menubar)
        self.menuEnrollments.setObjectName("menuEnrollments")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionManage_Students = QtWidgets.QAction(MainWindow)
        self.actionManage_Students.setObjectName("actionManage_Students")
        self.actionManage_Classes = QtWidgets.QAction(MainWindow)
        self.actionManage_Classes.setObjectName("actionManage_Classes")
        self.actionManage_Subjects = QtWidgets.QAction(MainWindow)
        self.actionManage_Subjects.setObjectName("actionManage_Subjects")
        self.actionEnroll_Students = QtWidgets.QAction(MainWindow)
        self.actionEnroll_Students.setObjectName("actionEnroll_Students")
        self.menuFile.addAction(self.actionExit)
        self.menuStudents.addAction(self.actionManage_Students)
        self.menuClasses.addAction(self.actionManage_Classes)
        self.menuSubjects.addAction(self.actionManage_Subjects)
        self.menuEnrollments.addAction(self.actionEnroll_Students)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuStudents.menuAction())
        self.menubar.addAction(self.menuClasses.menuAction())
        self.menubar.addAction(self.menuSubjects.menuAction())
        self.menubar.addAction(self.menuEnrollments.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "School mnagement"))
        self.label.setText(_translate("MainWindow", "مدیریت دانش آموزان"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuStudents.setTitle(_translate("MainWindow", "Students"))
        self.menuClasses.setTitle(_translate("MainWindow", "Classes"))
        self.menuSubjects.setTitle(_translate("MainWindow", "Subjects"))
        self.menuEnrollments.setTitle(_translate("MainWindow", "Enrollments"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionManage_Students.setText(_translate("MainWindow", "Manage Students"))
        self.actionManage_Classes.setText(_translate("MainWindow", "Manage Classes"))
        self.actionManage_Subjects.setText(_translate("MainWindow", "Manage Subjects"))
        self.actionEnroll_Students.setText(_translate("MainWindow", "Enroll Students"))
