# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\student_management.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(858, 825)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 170, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_firstname = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_firstname.setGeometry(QtCore.QRect(270, 30, 241, 51))
        self.lineEdit_firstname.setObjectName("lineEdit_firstname")
        self.lineEdit_lastname = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_lastname.setGeometry(QtCore.QRect(270, 110, 241, 51))
        self.lineEdit_lastname.setObjectName("lineEdit_lastname")
        self.lineEdit_classid = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_classid.setGeometry(QtCore.QRect(270, 190, 241, 51))
        self.lineEdit_classid.setObjectName("lineEdit_classid")
        self.pushButton_add_student = QtWidgets.QPushButton(Dialog)
        self.pushButton_add_student.setGeometry(QtCore.QRect(610, 30, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_add_student.setFont(font)
        self.pushButton_add_student.setObjectName("pushButton_add_student")
        self.pushButton_edit_student = QtWidgets.QPushButton(Dialog)
        self.pushButton_edit_student.setGeometry(QtCore.QRect(610, 110, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_edit_student.setFont(font)
        self.pushButton_edit_student.setObjectName("pushButton_edit_student")
        self.pushButton_delete_student = QtWidgets.QPushButton(Dialog)
        self.pushButton_delete_student.setGeometry(QtCore.QRect(610, 190, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_delete_student.setFont(font)
        self.pushButton_delete_student.setObjectName("pushButton_delete_student")
        self.tableWidget_students = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_students.setGeometry(QtCore.QRect(5, 271, 851, 551))
        self.tableWidget_students.setObjectName("tableWidget_students")
        self.tableWidget_students.setColumnCount(0)
        self.tableWidget_students.setRowCount(0)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Student management"))
        self.label.setText(_translate("Dialog", "firstname"))
        self.label_2.setText(_translate("Dialog", "lastname"))
        self.label_3.setText(_translate("Dialog", "class ID"))
        self.pushButton_add_student.setText(_translate("Dialog", "Add Student"))
        self.pushButton_edit_student.setText(_translate("Dialog", "Edit Student"))
        self.pushButton_delete_student.setText(_translate("Dialog", "Delete Student"))
